rule all:
    input:
        expand("{rscript}/{gset}/{tissue}-{dep}.pdf",
                rscript = ["cgasexp", "cgasdep"],
                gset = ["genes", "CIN", "MSigDB_Hallmark_2020", "GO_Biological_Process_2021", "DoRothEA"],
                tissue = ["pan", "BRCA"],
                dep = ["rnai", "ko"]),
        expand("cgasdrug/{gset}/{tissue}-{dep}.pdf",
                gset = ["genes", "CIN", "MSigDB_Hallmark_2020", "GO_Biological_Process_2021", "DoRothEA"],
                tissue = ["pan", "BRCA"],
                dep = ["drug"])

rule plot:
    input:
        rscript = "plot.r",
        infile = "{path}.rds"
    output:
        plotfile =  "{path}.pdf"
    shell:
        "Rscript {input.rscript}"
            " --infile {input.infile}"
            " --plotfile {output.plotfile}"

rule cgasdep:
    input:
        rscript = "cgas{type}.r"
    output:
        outfile = "cgas{type}/{gset}/{tissue}-{dep}.rds"
    shell:
        "Rscript {input.rscript}"
            " --tissue {wildcards.tissue}"
            " --dep {wildcards.dep}"
            " --set {wildcards.gset}"
            " --outfile {output.outfile}"
