rnaseq_exclude:
    SU_BT549_25_S32: "clone outlier"
    SU_BT549_26_S33: "clone outlier"
    SU_BT549_27_S34: "clone outlier"
    SU_WT_anti_IL6_rev_72h_S12: "bad RNA quality"

genesets:
    - GO_Biological_Process_2020
    - MSigDB_Hallmark_2020
    - DoRothEA
    - CORUM
    - HMDB_Metabolites
#    - miRTarBase_2017

# these are yaml files in expr_sets/* listing which genes, sets, viper TFs,
# etc to highlight via expr_cor/{diffcor,genenet}
# yamls need to be present in expr_sets and be referenced here for inclusion
expr_sets-highlight: [genes, sets, tfs] # stat needs fixing
