genesets:
    - KEA_2015
    - GO_Biological_Process_2018
    - GO_Cellular_Component_2018
    - GO_Molecular_Function_2018
    - ChEA_2016
    - ENCODE_and_ChEA_Consensus_TFs_from_ChIP-X
    - Reactome_2016
    - KEGG_2016
    - TargetScan_microRNA_2017
    - miRTarBase_2017
    - MSigDB_Oncogenic_Signatures
    - CH.HALLMARK
    - CORUM
    - HMDB_Metabolites
    - MILE_regulons

ins_plots: [ Erg, Ets1, Arid2, Drg1, Crebbp, Xrcc6, Trp53, Eif4enif1, Sfi1,
    Ikzf1, Pten, Suz12, Notch1, Rapgef6, Nf1, Lrba, Stat1, Hs6st3,
    Map3k5, Mapk9 ]

highlight_de: [ Erg, Ets1, Arid2, Crebbp, Trp53, Eif4enif1, Sox4, Pias1,
    Ikzf1, Pten, Suz12, Notch1, Rapgef6, Nf1, Lrba, Stat1 ]

# these are yaml files in expr_sets/* listing which genes, sets, viper TFs,
# etc to highlight via expr_cor/{diffcor,genenet}
# yamls need to be present in expr_sets and be referenced here for inclusion
expr_sets-highlight: [genes, sets, tfs] # stat needs fixing
