configfile: "../../config.yaml"

subworkflow sets:
    workdir: "../genesets"
    snakefile: "../genesets/Snakefile"

rule all:
    input:
        expand("sets/{sets}.pdf", sets=config['genesets'])

rule dset:
    input:
        rscript = "dset.r",
        yaml = "BT549_Stat1.yaml",
        expr = "count_matrix_known_barcodes_STL_and_USS_genes.txt"
    output:
        outfile = "dset.rds",
        plotfile = "dset.pdf"
    shell:
        "Rscript {input.rscript}"
            " --yaml {input.yaml}"
            " --expr {input.expr}"
            " --outfile {output.outfile}"
            " --plotfile {output.plotfile}"
