configfile: "../../config.yaml"

org = ['human', 'mouse']

rule all:
    input:
        expand("{org}/{geneset}.RData", org=org, geneset=config['genesets'])

rule enrichr:
    input:
        rscript = "make_set.r"
    output:
        human = "human/{geneset}.RData",
        mouse = "mouse/{geneset}.RData"
    shell:
        "Rscript {input.rscript}"
            " --geneset {wildcards.geneset}"
            " --human {output.human}"
            " --mouse {output.mouse}"
