configfile: "../config.yaml"

subworkflow genesets:
    workdir: "genesets"
    snakefile: "genesets/Snakefile"

rule all:
    input:
        "rnaseq.pdf",
        expand("gsva/{sets}.rds", sets=config['genesets'])

rule rnaseq:
    input:
        rscript = "rnaseq.r",
        samples = "rnaseq.tsv"
    output:
        outfile = "rnaseq.rds",
        plotfile = "rnaseq.pdf"
    shell:
        "Rscript {input.rscript}"
            " --samples {input.samples}"
            " --outfile {output.outfile}"
            " --plotfile {output.plotfile}"

rule gsva:
    input:
        rscript = "gsva.r",
        eset = "rnaseq.rds",
        setfile = genesets("human/{gset}.rds")
    output:
        outfile = "gsva/{gset}.rds"
    shell:
        "Rscript {input.rscript}"
            " --eset {input.eset}"
            " --setfile {input.setfile}"
            " --outfiel {output.outfile}"
